# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toast.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(507, 307)
        MainWindow.setStyleSheet("background:transparent")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-34, -30, 571, 351))
        self.label.setStyleSheet("border-image: url(:/newPrefix/dsBuffer.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.edit = QtWidgets.QPushButton(self.centralwidget)
        self.edit.setGeometry(QtCore.QRect(440, 235, 31, 31))
        self.edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit.setStyleSheet("border-image: url(:/newPrefix/pen.png);\n"
"")
        self.edit.setText("")
        self.edit.setObjectName("edit")
        self.copy = QtWidgets.QPushButton(self.centralwidget)
        self.copy.setGeometry(QtCore.QRect(340, 230, 41, 41))
        self.copy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copy.setStyleSheet("border-image: url(:/newPrefix/copy.png);")
        self.copy.setText("")
        self.copy.setObjectName("copy")
        self.hparleur = QtWidgets.QPushButton(self.centralwidget)
        self.hparleur.setGeometry(QtCore.QRect(390, 236, 31, 31))
        self.hparleur.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hparleur.setStyleSheet("border-image: url(:/newPrefix/hp.png);")
        self.hparleur.setText("")
        self.hparleur.setObjectName("hparleur")
        self.close = QtWidgets.QPushButton(self.centralwidget)
        self.close.setGeometry(QtCore.QRect(0, 0, 31, 23))
        self.close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close.setStyleSheet("background:transparent;\n"
"color: rgb(255, 0, 0);\n"
"font: 75 15pt \"MS Shell Dlg 2\";")
        self.close.setObjectName("close")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 250, 151, 20))
        self.label_3.setObjectName("label_3")
        self.actualiser = QtWidgets.QPushButton(self.centralwidget)
        self.actualiser.setGeometry(QtCore.QRect(300, 238, 31, 31))
        self.actualiser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.actualiser.setStyleSheet("border-image: url(:/newPrefix/act (2).png);")
        self.actualiser.setText("")
        self.actualiser.setObjectName("actualiser")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 30, 441, 191))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.text = QtWidgets.QTextEdit(self.page)
        self.text.setGeometry(QtCore.QRect(10, 10, 431, 151))
        self.text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.text.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color:transparent;\n"
"color:white;\n"
"border:transparent;")
        self.text.setReadOnly(True)
        self.text.setObjectName("text")
        self.auteur = QtWidgets.QLabel(self.page)
        self.auteur.setGeometry(QtCore.QRect(260, 160, 181, 31))
        self.auteur.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.auteur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.auteur.setObjectName("auteur")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.text_cita = QtWidgets.QTextEdit(self.page_2)
        self.text_cita.setGeometry(QtCore.QRect(20, 20, 401, 81))
        self.text_cita.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"border:1px solid #fff;")
        self.text_cita.setObjectName("text_cita")
        self.auteur_cita = QtWidgets.QLineEdit(self.page_2)
        self.auteur_cita.setGeometry(QtCore.QRect(100, 120, 321, 31))
        self.auteur_cita.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.auteur_cita.setObjectName("auteur_cita")
        self.valider = QtWidgets.QPushButton(self.page_2)
        self.valider.setGeometry(QtCore.QRect(334, 160, 91, 23))
        self.valider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.valider.setStyleSheet("\n"
"border:1px solid #fff;\n"
"border-left:none;\n"
"border-right:none;\n"
"border-top:none;\n"
"color: rgb(255, 255, 255);")
        self.valider.setObjectName("valider")
        self.annuler = QtWidgets.QPushButton(self.page_2)
        self.annuler.setGeometry(QtCore.QRect(220, 160, 91, 23))
        self.annuler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.annuler.setStyleSheet("\n"
"border:1px solid #f00;\n"
"border-left:none;\n"
"border-right:none;\n"
"border-top:none;\n"
"color: rgb(255, 255, 255);")
        self.annuler.setObjectName("annuler")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 507, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.close.setText(_translate("MainWindow", "x"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; color:#ff0000;\">l\'Amour</span><span style=\" font-size:7pt; color:#ffffff;\"> ta plus belle arme !</span></p></body></html>"))
        self.text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">text</p></body></html>"))
        self.auteur.setText(_translate("MainWindow", "h"))
        self.text_cita.setPlaceholderText(_translate("MainWindow", "Citation ..."))
        self.auteur_cita.setPlaceholderText(_translate("MainWindow", "auteur"))
        self.valider.setText(_translate("MainWindow", "VALIDER"))
        self.annuler.setText(_translate("MainWindow", "RETOUR"))
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
